version: 2
updates:
- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: weekly
  reviewers:
  - lewisgoddard
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  reviewers:
  - lewisgoddard
  allow:
    - dependency-type: "all"
  groups:
    npm-patching:
      update-types:
        - "minor"
        - "patch"
- package-ecosystem: composer
  directory: "/_backend"
  schedule:
    interval: weekly
  reviewers:
  - lewisgoddard
  allow:
    - dependency-type: "all"
  groups:
    composer-patching:
      update-types:
        - "minor"
        - "patch"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  reviewers:
  - lewisgoddard
  groups:
    gha-patching:
      update-types:
        - "minor"
        - "patch"
