---

name: CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # v2.37.1
        with:
          php-version: 8.1 # This PHP version matches the server.
          tools: composer

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 18 # This Node version matches the server.

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build
