---

name: Lint

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  Lint:
    name: Lint (${{ matrix.label }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - label: CSS
            command: npx stylelint "_styles/**/*.css" --custom-formatter @csstools/stylelint-formatter-github
          - label: JS
            command: ./_tests/javascript.sh
          - label: PHP
            command: ./_tests/php.sh
          - label: Translations
            command: php ./_tests/translations.php

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # v2.37.1
        with:
          php-version: '8.5'
          tools: composer

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'

      - name: Install
        run: npm ci

      - name: Lint
        run: ${{ matrix.command }}
